# Sendgrid API configuration
sendgrid_api: <sendgrid-api-key>

# notification settings
email_from: email@domain.com
email_subject: Public GitHub repos detected
email_template: templates/notice.html
email_notify:
    - user1@domain.com,User One
    - user2@domain.com,User Two
    - user3@domain.com

#These api keys are used for authentication to kickstart the audit process
controller_apikeys:
    - <access-key-1>
    - <access-key-2>

github_api: <github-api-key>

# List of github accounts to scan
github_scan:
    - Google
    - Unitato

# This setting is used to whitelist repositories from notification.
github_whitelist:
    - felix
    - rails-composer
    #- scripts
    - VirusTotalApi
    #- secret-repo
